- Added progress start to waiting process - Fixed and improved flanneld and docker startup order - Checking docker version

diff --git a/qk8s b/qk8s
--- a/qk8s
+++ b/qk8s
@@ -1,5 +1,4 @@
-#!/usr/bin/env bash
-
+#!/usr/bin/env bash 
 #Choosing the default gateway interface
 INET_INTERFACE=`netstat -rn | head -3 | tail -1 | awk '{print $8}'`
 #Install directory by default
@@ -14,6 +13,14 @@ K8S_MASTER=$3
 function command_exists() {
         if [ `which "$1"` ]; then
 		echo "INFO - found $1 command"
+		if [ "$1" == "docker" ]; then
+			echo "INFO - Cheecking the correct version of $1"
+			dpkg -L docker.io 2> /dev/null 1>/dev/null
+			if [ $? -eq 0 ]; then
+				echo "ERROR - Docker (docker.io) from apt sources installed. Please, remove it and let qk8s install the official one (docker-engine)"
+				exit 2
+			fi
+		fi
 	else
 		if [ "$1" == "kubectl" ]; then
 			read -r -p "Kubectl not found. Do want me to install it on $INSTALL_DIR/bin? [Y/n] " response
@@ -74,6 +81,7 @@ function check_system {
 	mkdir -p $INSTALL_DIR/{bin,etc/kubernetes/manifests,logs,run,kubelet,certs}
 
 	command_exists kubectl
+
 	echo "INFO - Installing Flanneld overlay network daemon"
 	curl -s -L -o /tmp/flannel-0.5.5-linux-amd64.tar.gz https://github.com/coreos/flannel/releases/download/v0.5.5/flannel-0.5.5-linux-amd64.tar.gz ; tar -xzf /tmp/flannel-0.5.5-linux-amd64.tar.gz -C /tmp ; cp /tmp/flannel-0.5.5/flanneld ${INSTALL_DIR}/bin/ ; rm -rf /tmp/flannel-0.5.5*
 
@@ -118,9 +126,16 @@ EOF
 }
 
 function config_flannel_master {
-
-curl -X PUT -d "value={\"Network\":\"10.0.0.0/16\",\"Backend\":{\"Type\":\"vxlan\"}}" "http://${K8S_HOSTNAME}:4001/v2/keys/flannel/network/config"
-
+	echo "INFO - Wainting to etcd service to start to set flanneld configuration"
+	spin='-\|/'
+	i=0
+	while ! nc -z ${K8S_HOSTNAME} 4001; do
+		i=$(( (i+1) %4 ))
+		printf "\r${spin:$i:1}"
+		sleep .5
+	done
+	curl -X PUT -d "value={\"Network\":\"10.0.0.0/16\",\"Backend\":{\"Type\":\"vxlan\"}}" "http://${K8S_HOSTNAME}:4001/v2/keys/flannel/network/config"
+	echo "INFO - Flanneld configuration stored in etcd"
 }
 
 function start_kubelet_master {
@@ -236,12 +251,12 @@ function start_kubernetes_master {
 	check_system
 	download_kubelet
 	copy_kubelet_manifests_master
+	start_kubelet_master
+	config_flannel_master
 	start_flannel_master
 	prepare_docker
-	start_kubelet_master
 	config_kubectl_master
 	wait_for_kubernetes
-	config_flannel_master
 	create_k8s_system_namespace
 	echo "INFO - Started master kubernetes version $K8S_VERSION"
 	$K8S_CLIENT cluster-info
@@ -286,7 +301,9 @@ function delete_files {
 	rm -rf $INSTALL_DIR/etc
 	rm -rf $INSTALL_DIR/logs
 	rm -rf $INSTALL_DIR/run
-	rm -rf $INSTALL_DIR/kubelet
+	rm -rf $INSTALL_DIR/bin
+	rm -rf $INSTALL_DIR/certs
+	rm -rf /run/flannel/subnet.env
 }
 
 function restore_docker {
@@ -316,10 +333,17 @@ function addon_kubernetes {
 }
 
 function wait_for_kubernetes {
+	spin='-\|/'
+	i=0
 	echo "INFO - Waiting for kubernetes to become ready"
 	until $($K8S_CLIENT cluster-info &> /dev/null); do
-		sleep 1
+		i=$(( (i+1) %4 ))
+		printf "\r${spin:$i:1}"
+		sleep .5
 	done
+
+
+
 }
 
 function print_usage {
